/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateIndexRouteImport } from './routes/create/index'
import { Route as ProfileUserIdRouteImport } from './routes/profile/$userId'
import { Route as PlayerVideoIdRouteImport } from './routes/player/$videoId'
import { Route as PageTermsRouteImport } from './routes/page/terms'
import { Route as PagePrivacyRouteImport } from './routes/page/privacy'
import { Route as PageAboutRouteImport } from './routes/page/about'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateIndexRoute = CreateIndexRouteImport.update({
  id: '/create/',
  path: '/create/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerVideoIdRoute = PlayerVideoIdRouteImport.update({
  id: '/player/$videoId',
  path: '/player/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)
const PageTermsRoute = PageTermsRouteImport.update({
  id: '/page/terms',
  path: '/page/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PagePrivacyRoute = PagePrivacyRouteImport.update({
  id: '/page/privacy',
  path: '/page/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PageAboutRoute = PageAboutRouteImport.update({
  id: '/page/about',
  path: '/page/about',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/page/about': typeof PageAboutRoute
  '/page/privacy': typeof PagePrivacyRoute
  '/page/terms': typeof PageTermsRoute
  '/player/$videoId': typeof PlayerVideoIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/create/': typeof CreateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/page/about': typeof PageAboutRoute
  '/page/privacy': typeof PagePrivacyRoute
  '/page/terms': typeof PageTermsRoute
  '/player/$videoId': typeof PlayerVideoIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/create': typeof CreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/page/about': typeof PageAboutRoute
  '/page/privacy': typeof PagePrivacyRoute
  '/page/terms': typeof PageTermsRoute
  '/player/$videoId': typeof PlayerVideoIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/create/': typeof CreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/page/about'
    | '/page/privacy'
    | '/page/terms'
    | '/player/$videoId'
    | '/profile/$userId'
    | '/create/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/page/about'
    | '/page/privacy'
    | '/page/terms'
    | '/player/$videoId'
    | '/profile/$userId'
    | '/create'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/page/about'
    | '/page/privacy'
    | '/page/terms'
    | '/player/$videoId'
    | '/profile/$userId'
    | '/create/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PageAboutRoute: typeof PageAboutRoute
  PagePrivacyRoute: typeof PagePrivacyRoute
  PageTermsRoute: typeof PageTermsRoute
  PlayerVideoIdRoute: typeof PlayerVideoIdRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
  CreateIndexRoute: typeof CreateIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/': {
      id: '/create/'
      path: '/create'
      fullPath: '/create/'
      preLoaderRoute: typeof CreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$videoId': {
      id: '/player/$videoId'
      path: '/player/$videoId'
      fullPath: '/player/$videoId'
      preLoaderRoute: typeof PlayerVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page/terms': {
      id: '/page/terms'
      path: '/page/terms'
      fullPath: '/page/terms'
      preLoaderRoute: typeof PageTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page/privacy': {
      id: '/page/privacy'
      path: '/page/privacy'
      fullPath: '/page/privacy'
      preLoaderRoute: typeof PagePrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page/about': {
      id: '/page/about'
      path: '/page/about'
      fullPath: '/page/about'
      preLoaderRoute: typeof PageAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PageAboutRoute: PageAboutRoute,
  PagePrivacyRoute: PagePrivacyRoute,
  PageTermsRoute: PageTermsRoute,
  PlayerVideoIdRoute: PlayerVideoIdRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
  CreateIndexRoute: CreateIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
